### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by CaroleB** [UMNLibraries/ojs-gopher-theme#4]
Thank you for this theme ! 

I noticed a bug with the label ##plugins.themes.gopher.makeSubmission## on the button :

![image](https://github.com/UMNLibraries/ojs-gopher-theme/assets/10991398/33aedebb-ffc9-471d-b942-3f0479c030fa)

Maybe the french traduction is absent ?

**Comment by johnbarneson** [comment]
Thanks for reporting. There is not a French translation. I will try to add one.

**Comment by CaroleB** [comment]
Thank you ! Yes, it's the "Submission" button. 
I added a translation file in a pull request.
